version: '2'

services:
  backend:
    build: './backend'
    command: sh -c 'nodemon index.js -i cache'
    volumes:
      - ./backend:/backend
      - /backend/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:80"
    network_mode: 'bridge'
    links:
      - redis:redis

  redis:
    image: smebberson/alpine-redis
    network_mode: 'bridge'
    ports:
      - "6379:6379"

  ide:
    build: './ide'
    command: sh -c 'nodemon index.js'
    volumes:
      - ./ide:/ide
      - /idenode_modules
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8001:80"
    network_mode: 'bridge'
    links:
      - redis:redis

  ui:
    build: './ui'
    command: npm start
    volumes:
      - ./ui:/ui
      - /ui/node_modules
      - /ui/bower_components
    ports:
      - '80:4200'
